### ISSUE TITLE
Input stream based key rings

### ISSUE THREAD

**Issue by mcanlas** [neuhalje/bouncy-gpg#13]
It'd be cool to have a class that consumes input streams to get the key rings. That seems to be how it works under the hood.

**Comment by neuhalje** [comment]
Good idea :-)

**Comment by mcanlas** [comment]
Dope, thank you for responding to this and #12 so quickly. Any plans on cutting a release? Been enjoying your library very much.

**Comment by neuhalje** [comment]
Thanks 😀

A new release is planned for „when I get the documentation flying“. Also I need to find out how to best mark certain portions (symmetric key derivation) as „alpha and like likely to change“.

In measurable units that would be „within the next month“.
