### ISSUE TITLE
Writing Keyrings to storage

### ISSUE THREAD

**Issue by vanitasvitae** [neuhalje/bouncy-gpg#21]
Hi!
I noticed, that Bouncy-GPG for now only focusses on reading keyrings from files etc.
Is support for writing modified keyrings planned as well?

**Comment by neuhalje** [comment]
I ain't not dead yet :-) .... just a lot of "real world TODOs" .... nothing is really planed, I go on a "what the users need" base

**Comment by vanitasvitae** [comment]
Just for the record: I decided to create my own library due to limited time and me constantly breaking your test cases :laughing:. I'm following a similar pattern as your library though, so you might still be able to pick some of my code and port it to bouncy-gpg :)

**Comment by neuhalje** [comment]
You are welcome! Copy as much as you want — that ist what FOSS is for! 😊

**Comment by vanitasvitae** [comment]
> Copy as much as you want — that ist what FOSS is for! :blush:

Same for you obviously :)

**Comment by jrobens** [comment]
Is this about the gpg2 secret key format where the keys are stored in private-keys-v1.d directory in individual files or reading from some secrets provider, sql, nosql etc provider? 
I'm interested in both, but gpg2 format first.

**Comment by neuhalje** [comment]
@jrobens Haven't decided yet - depends on what BouncyCastle provides for this

@vanitasvitae : What does your implementation support?

**Comment by vanitasvitae** [comment]
PGPainless currently has no real API for writing keys. If a user wants to write keys/keyrings to file, they must use the BC methods for now. Still, creating a simple API for writing is definitely something on my TODO list.

**Comment by neuhalje** [comment]
@jrobens  storing keys in a store of your own application is recommended.  I wrote [a reasoning](https://github.com/neuhalje/bouncy-gpg/issues/22#issuecomment-406848767) for why using `gpg`s storage is most likely not the best course of action.

**Comment by neuhalje** [comment]
@jrobens : Thanks!
