### ISSUE TITLE
question about gnupg v2.1+ secring.pgp

### ISSUE THREAD

**Issue by zcaudate** [neuhalje/bouncy-gpg#22]
In the readme, you mentioned `Use the other methods to read private keys`.

Would you give an example of how this can be done?

**Comment by neuhalje** [comment]
## On using (sec|pub)ring.gpg

*I strongly advise against using `secring.gpg` or `pubring.gpg` for production systems*. These files are an undocumented API of gnupg: usable, but can change or show unexpected results. E.g. with GPG 2.1 the `secring.gpg` file gets no longer updated [and will provide you with stale data](https://gnupg.org/faq/whats-new-in-2.1.html#nosecring) (emphasis by me):

> To ease the migration to the no-secring method, gpg detects the presence of a secring.gpg and converts the keys on-the-fly to the the key store of gpg-agent (this is the private-keys-v1.d directory below the GnuPG home directory (~/.gnupg)). **This is done only once and an existing secring.gpg is then not anymore touched by gpg.** This allows co-existence of older GnuPG versions with GnuPG 2.1. However, any change to the private keys using the new gpg will not show up when using pre-2.1 versions of GnuPG and vice versa.

## Recommendation: InMemoryKeyring

Most applications should manage their keys in an application specific database. Though this might seem more complex than just using the existing keyring files it has a some nice advantages:

* No dependency on the `gpg` executable 
* Keys can be managed remotely (e.g. via the applications database)
* Key management is enforced to happen via the application
* Key management for distributed (_scale out_ / _cloud_) systems is much easier when keys are not managed by the operating system 

### HOWTO use InMemoryKeyring

To use the  [InMemoryKeyring](https://github.com/neuhalje/bouncy-gpg/blob/master/src/main/java/name/neuhalfen/projects/crypto/bouncycastle/openpgp/keys/keyrings/KeyringConfigs.java) you first need to export the keys. Then you put them in your  application data(base).

#### Exporting the keys from gpg

Export the keys  with `gpg` (`gpg --export-secret-key -a user@example.com` and `gpg --export -a user@example.com`):

```text
gpg --export -a user@example.com > user@example.com.pub.gpg
cat user@example.com.pub.gpg

-----BEGIN PGP PUBLIC KEY BLOCK-----
...
-----END PGP PUBLIC KEY BLOCK-----

# You need to input keys passphrase here
gpg --export-secret-key -a user@example.com > user@example.com.secret.gpg
cat user@example.com.secret.gpg

-----BEGIN PGP PRIVATE KEY BLOCK-----
...
-----END PGP PRIVATE KEY BLOCK-----
```

#### Importing the keys

A few examples for using the [InMemoryKeyring](https://github.com/neuhalje/bouncy-gpg/blob/master/src/main/java/name/neuhalfen/projects/crypto/bouncycastle/openpgp/keys/keyrings/KeyringConfigs.java)  can be found in the [Test code](https://github.com/neuhalje/bouncy-gpg/blob/master/src/test/java/name/neuhalfen/projects/crypto/bouncycastle/openpgp/testtooling/Configs.java).

Here is the short version:

```java
  public static KeyringConfig keyringConfigInMemoryForKeys(final String exportedPubKey, final String exportedPrivateKey, final String passphrase) throws IOException, PGPException {

    final InMemoryKeyring keyring = KeyringConfigs.forGpgExportedKeys(KeyringConfigCallbacks.withPassword(passphrase);

    keyring.addPublicKey(exportedPubKey.getBytes("US-ASCII"));
   // you can add many more public keys

    keyring.addSecretKey(exportedPrivateKey.getBytes("US-ASCII"));
   // you can add many more privvate keys

    return keyring;
  }
```


#### Using the config

```java

final InMemoryKeyring keyring = keyringConfigInMemoryForKeys(...);

final InputStream decryptedPlaintextStream = BouncyGPG
        .decryptAndVerifyStream()
        .withConfig(keyring)
        ....
```

**Comment by neuhalje** [comment]
@zcaudate - did this answer you question?

**Comment by zcaudate** [comment]
Yes. That was awesome. I didn’t expect that.  Thanks for such a comprehensive summary.

**Comment by neuhalje** [comment]
You are welcome!
