### ISSUE TITLE
how to generate an openpgp key?

### ISSUE THREAD

**Issue by zcaudate** [neuhalje/bouncy-gpg#23]
There are examples on how to read a key that is exported. I'm looking for a way to generate a key directly using the library. Are there examples on how to do this?

**Comment by codesandnotes** [comment]
There is an issue opened for key generation ([Issue #20](https://github.com/neuhalje/bouncy-gpg/issues/20)). As far as I know this feature is not yet implemented in BouncyGPG... In the meantime, maybe [this](https://github.com/codesandnotes/openpgp-integration/tree/java-key-generation) will help: https://www.codesandnotes.be/2018/07/17/openpgp-java-keys-generation/

**Comment by zcaudate** [comment]
@neuhalje that would be great.

**Comment by neuhalje** [comment]
FYI -- I am currently working on it

**Comment by zcaudate** [comment]
thanks so much for this. looking forward to it.

**Comment by neuhalje** [comment]
@zcaudate The implementation looks _quite_ good (if you want, I'd welcome feedback on the API design behind `BouncyGPG::createSimpleKeyring` and `BouncyGPG::createKeyring`)

**Comment by neuhalje** [comment]
Quick update: I ran into some blockers with ECC key generation (failing integration tests, see #30 )

**Comment by neuhalje** [comment]
v2.2.0 released with RSA key generation
