### ISSUE TITLE
Not null requirement for Keyring Config

### ISSUE THREAD

**Issue by mkmeral** [neuhalje/bouncy-gpg#37]
Keyring config requires private key public key and password to be not null, even when they are not used. For example, even to only encrypt with public key (not signing) it requires those to be non null. Current workaround I found is to give empty string for password and random file for private key (because it creates an input stream from file). 

The problem I specifically have is at (public class Rfc4880KeySelectionStrategy implements KeySelectionStrategy:137) and the reason it gives an error is, it tries to get secret keyrings before checking what the purpose is, So a simple solution for this specific problem would be to move line 137 inside the switch statement. However, I don't have extended knowledge of this project, so I am not sure if that is the optimal solution

**Comment by neuhalje** [comment]
@mkmeral : Working on it. Is there a specific reason why you use the `FileBasedKeyringConfig`? I strongly recommend to switch to `InMemoryKeyring` because it is not dependend on gpg internals.

See [here](https://github.com/neuhalje/bouncy-gpg#on-using-secpubringgpg) for more reasons to do so.

**Comment by neuhalje** [comment]
I moved `getSecretKeyRings` [into the conditional](https://github.com/neuhalje/bouncy-gpg/blob/aa35a820e871c4ca83d238976241990cd73f5b4c/src/main/java/name/neuhalfen/projects/crypto/bouncycastle/openpgp/keys/callbacks/Rfc4880KeySelectionStrategy.java#L139) in commit aa35a82 

Can you test with the version in GitHub?

**Comment by neuhalje** [comment]
Or with 2.2.0

**Comment by mkmeral** [comment]
@neuhalje : Yeah, I have later changed it to InMemoryKeyring, and I am using it like that right now. I won't be able to test it right now, since that would require for me to revert commits.  I will be able to test probably in 2 weeks, I will write back on the results.

**Comment by neuhalje** [comment]
Since InMemoryKeyring is the future I am inclined to close this
