### ISSUE TITLE
Missing Maven pom.xml in Project root

### ISSUE THREAD

**Issue by michaelthecsguy** [neuhalje/bouncy-gpg#40]
Before, there was a pom.xml at the project root.  Since the release of 2.2.0, it's missing.  Can you add it back?

**Comment by neuhalje** [comment]
Hi @michaelthecsguy,

the only `pom.xml` the project features is (still) in `examples/maven/pom.xml`. Are you looking for that one?

**Comment by michaelthecsguy** [comment]
No... it was at the project root before.  I was not referring to examples/maven/ 
Sorry for the late reply because I had to attend the work conference. @neuhalje

**Comment by neuhalje** [comment]
@michaelthecsguy: I just checked, there as never been a `pom.xml` in the root of the project:

```sh
$ git log --name-status --format="" --all --full-history -- "**/pom.xml"

M	examples/maven/pom.xml
M	examples/maven/pom.xml
M	examples/maven/pom.xml
M	examples/maven/pom.xml
M	examples/maven/pom.xml
M	examples/maven/pom.xml
M	examples/maven/pom.xml
M	examples/maven/pom.xml
M	examples/maven/pom.xml
M	examples/maven/pom.xml
M	examples/maven/pom.xml
M	examples/maven/pom.xml
M	examples/maven/pom.xml
A	examples/maven/pom.xml

```

**Comment by neuhalje** [comment]
There is some `pom.xml` related documentation in the [README](https://github.com/neuhalje/bouncy-gpg#maven)

**Comment by michaelthecsguy** [comment]
@neuhalje thanks putting it on public maven artifact repository
