### ISSUE TITLE
LOOKING FOR MAINTAINER

### ISSUE THREAD

**Issue by neuhalje** [neuhalje/bouncy-gpg#72]
Please comment, if you want to become the new maintainer

**Comment by unverbraucht** [comment]
I have little time myself but am happy to merge the outstanding PRs, bump dependencies and create releases. Happy to discuss via email / other means @neuhalje :)

**Comment by xSAVIKx** [comment]
Hey @neuhalje, I'm open to helping review PRs and updating some deps as well.

E.g. I have a project that has to move forward with bouncycastle 1.77 but we're also using your great library.

**Comment by neuhalje** [comment]
Kevin, Yurii - Thank you so much. I added you as collaborators.

**Comment by neuhalje** [comment]
@unverbraucht / @xSAVIKx We need to think about how to publish this lib. [AFAIR the implemented ](https://github.com/neuhalje/bouncy-gpg/issues/79)

**Comment by unverbraucht** [comment]
@neuhalje I dropped the ball on this and waited for the invitation to expire. Could you re-invite me please?
