### ISSUE TITLE
Your Codeberg mirror has became a nest for spammers!

### ISSUE THREAD

**Issue by throwaway-d** [neuhalje/bouncy-gpg#74]
You should moderate them and report them to any security corps/orgs and Codeberg themselves!

**Comment by throwaway-d** [comment]
https://codeberg.org/Codeberg/Community/issues/1293
Since your repo hasn't been maintained and updated for a very long time, maybe just temporarily disable creating issues on your Codeberg mirror?

**Comment by neuhalje** [comment]
Hey @throwaway-d  - late to the party but thank you for the pointer. "Problem solved" :-)
